### ISSUE TITLE
Integrate Functioning Navigation

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#10]
Create all navigation links between views in Xcode and test on device. Exceptions will be views related to user profile creation and perhaps messaging and payment, as those may not be implemented yet.

**Comment by Ryan-Korteway** [comment]
Not to mention what happens to the app/views if access to the firebase backend is not present for signing into the app or pulling down the pins/location info's for the drivers because there is no network at the time of needing those functions.
