### ISSUE TITLE
Integrate Profile Management and Data Storage API

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#11]
Write the code that implements data storage for user profiles, including any authorization requirements with keys, etc.

**Comment by Ryan-Korteway** [comment]
Once the UI is in place for account creation and sign in, I should be able to make the model/view controller back end code that will allow for use to store stuff to firebase profile wise

As for profile management, if we go with the account creation and log in via email addresses and passwords, Firebase automates that for us as well once we implement the right "click here for forgotten passwords" links etc in the app itself.
