### ISSUE TITLE
Create a "How it Works" Section

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#12]
We should probably have a "How it Works" page on the app. This could also be the first page a user is directed to when they open the app for the first time.

**Comment by Ryan-Korteway** [comment]
I agree with this sentiment, I think as a first time opened pop up, this is a good idea, also just have it be accessible as its own screen with a tap on a question mark icon or something on the main page of the app perhaps?

**Comment by Ryan-Korteway** [comment]
Okay I have the screenshots and their respective labels although going through and making the tutorial has left me wondering about a few small things about our UI that I plan on asking about this afternoon during our meetings.
