### ISSUE TITLE
Research Real-Time Pin Locations

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#15]
How do we show real-time locations of drivers on a map?

**Comment by Ryan-Korteway** [comment]
Havent researched this yet but at one point in our summer course, we did do automated pin creation through having the latitude and longitude of what where we wanted to drop the pin so in my mind doing so would be best done by just having the maps in the app fill up themselves with the lat/longs of the drivers every few minutes, sadly that would be rather jerky and probably eat up a lot of battery too so some additional research for something more fluid probably wouldnt be a bad idea.

**Comment by Ryan-Korteway** [comment]
realtime pins researched and partially implemented. working on finishing their implementation.
