### ISSUE TITLE
Integrate Notifications

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#19]
If we decide on in-app messaging, let's implement it now.

**Comment by Ryan-Korteway** [comment]
I really don't see the need to implement in app messaging unless we need an extra feature to help boost our grade.

My stance is there is no way we can come up with something as good/stable as imessages so lets just make it really easy/fast to segway from our app to imessages or the built in phone app for calling the driver.

**Comment by Ryan-Korteway** [comment]
I will be looking into this in my own branch hopefully at some point tonight.

**Comment by Ryan-Korteway** [comment]
may need some tweaking in the titles, custom actions, etc etc but it should all be in place and ready.
