### ISSUE TITLE
Research Topics

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#3]
Identify how/what tools will be used to implement these features:

- User profile management/data storage
- Messaging between users (built-in or share phone number?)
- Payments (PayPal, Venmo, etc)

**Comment by chrismic** [comment]
We have a while before we have to worry about this but I think we should look into some legal stuff before we release it like what do we put in our user agreement because we would basically be storing peoples information and have access to their location so we absolutely need to research that.

**Comment by Ryan-Korteway** [comment]
Yes in my mind we need to be very clear and upfront about what info we collect and what we do/dont do to try and keep our users safe. Like you said back in the library Michael, Uber knows so much about the drivers that they could never really get away with it. For us the most we are doing to verify that the users are like GV people and whatever is making them sign up/log in with a GVSU email address. 

which is also why I want to make sure that we have some sort of "whom has ridden with whom" feature.

**Comment by nickheady** [comment]
We should track, and have available to us, details about every ride. The users of course should (if we have time) have access to their own records.
