### ISSUE TITLE
Research Messaging

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#5]
How will users communicate?
Will it be implement in-app, or will they have to use iMessage/standard texting?

**Comment by Ryan-Korteway** [comment]
Mike and I are of the same mindset of not reinventing the wheel and instead just sharing phone numbers securely through the app/firebase and then providing some buttons next to the phone numbers on the driver profiles to autostart a call or send a text through/to that phone number in the app.

**Comment by nickheady** [comment]
I agree.
