### ISSUE TITLE
Research Payment

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#6]
How will drivers be paid? Cash? Paypal? Apple Pay?

**Comment by Ryan-Korteway** [comment]
integration of braintree payments will allow for payments through credit/debit cards, apple pay, bitcoin, venmo, android pay (not that it matters), masterpass, and visa express or something like that?

So once its understood and implemented, it should be good. I have done research on the options braintree offers but not the actual process of implementation either in app or in back end and it looks like the backend we might have to set up ourselves unfortunately....

**Comment by nickheady** [comment]
Looks like we are going with Venmo, by providing a link to the rider to open in Safari/Venmo app and pay the driver.
