### ISSUE TITLE
Create Wire Diagram

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#8]
Create a drawn out wire diagram that shows all views and navigation flows.

**Comment by Ryan-Korteway** [comment]
I have a personal 3'x4' whiteboard in my apartment that I could do this one but at the same time you are the one in charge of the UI at this point so if you would like to do this I would totally understand.

**Comment by nickheady** [comment]
Working on the diagram in Xcode now. It'll vary a bit from yours but we'll be refining it throughout the project anyway.
